name: Q:\Conda_Envs\tf_env
channels:
  - defaults
dependencies:
  - _tflow_select=2.3.0=mkl
  - abseil-cpp=20211102.0=hd77b12b_0
  - absl-py=2.1.0=py39haa95532_0
  - aiodns=3.5.0=py39haa95532_0
  - aiohappyeyeballs=2.6.1=py39haa95532_0
  - aiohttp=3.12.15=py39h02ab6af_0
  - aiosignal=1.4.0=py39haa95532_0
  - astunparse=1.6.3=py_0
  - async-timeout=5.0.1=py39haa95532_0
  - attrs=25.4.0=py39haa95532_1
  - blas=1.0=mkl
  - bottleneck=1.4.2=py39hc99e966_0
  - brotlicffi=1.0.9.2=py39h885b0b7_2
  - bzip2=1.0.8=h2bbff1b_6
  - c-ares=1.34.5=h731ff69_0
  - ca-certificates=2025.12.2=haa95532_0
  - cachetools=4.2.2=pyhd3eb1b0_0
  - certifi=2025.10.5=py39haa95532_0
  - cffi=2.0.0=py39h02ab6af_0
  - charset-normalizer=3.4.4=py39haa95532_0
  - click=8.1.8=py39haa95532_0
  - colorama=0.4.6=py39haa95532_0
  - contourpy=1.2.1=py39h214f63a_1
  - cryptography=46.0.2=py39h114bc41_0
  - cudatoolkit=11.8.0=hd77b12b_0
  - cudnn=8.9.2.26=cuda11_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cython=3.1.4=py39h02ab6af_0
  - et_xmlfile=2.0.0=py39haa95532_0
  - expat=2.7.3=h885b0b7_4
  - flatbuffers=25.2.10=hbdc3ed3_0
  - fonttools=4.60.1=py39h02ab6af_0
  - freetype=2.13.3=h0620614_0
  - frozenlist=1.8.0=py39h885b0b7_0
  - gast=0.4.0=pyhd3eb1b0_0
  - giflib=5.2.2=h7edc060_0
  - google-auth=1.28.0=pyhd3eb1b0_0
  - google-auth-oauthlib=0.4.4=pyhd3eb1b0_0
  - google-pasta=0.2.0=pyhd3eb1b0_0
  - grpc-cpp=1.48.2=hf108199_0
  - grpcio=1.48.2=py39hf108199_0
  - h5py=3.14.0=py39h6fc9867_0
  - hdf5=1.14.5=ha36df97_2
  - icc_rt=2022.1.0=h6049295_2
  - icu=58.2=ha925a31_3
  - idna=3.11=py39haa95532_0
  - importlib-metadata=8.5.0=py39haa95532_0
  - importlib_resources=6.5.2=py39haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - joblib=1.5.2=py39haa95532_0
  - jpeg=9f=ha349fce_0
  - keras=2.10.0=py39haa95532_0
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - kiwisolver=1.4.4=py39hd77b12b_0
  - krb5=1.20.1=h5b6d351_1
  - lcms2=2.16=hb4a4139_0
  - lerc=3.0=hd77b12b_0
  - libclang13=14.0.6=default_h8e68704_2
  - libcurl=8.14.1=ha9f67de_0
  - libdeflate=1.17=h2bbff1b_1
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libpng=1.6.50=h46444df_0
  - libpq=12.15=hb652d5d_1
  - libprotobuf=3.20.3=h23ce68f_0
  - libssh2=1.10.0=hcd4344a_2
  - libtiff=4.5.1=hd77b12b_0
  - libuv=1.48.0=h827c3e9_0
  - libwebp-base=1.6.0=hbf3958f_0
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markdown=3.8=py39haa95532_0
  - markupsafe=3.0.2=py39h827c3e9_0
  - matplotlib=3.9.2=py39haa95532_1
  - matplotlib-base=3.9.2=py39he19b0ae_1
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py39h827c3e9_2
  - mkl_fft=1.3.11=py39h827c3e9_0
  - mkl_random=1.2.8=py39hc64d2fc_0
  - mpi=1.0=msmpi
  - mpi4py=4.0.3=py39h827c3e9_0
  - msmpi=10.1.1=had4844c_0
  - msys2-conda-epoch=20160418=1
  - multidict=6.7.0=py39h02ab6af_0
  - numexpr=2.10.1=py39h4cd664f_0
  - numpy=1.26.4=py39h055cbcc_0
  - numpy-base=1.26.4=py39h65a83cf_0
  - oauthlib=3.3.1=py39haa95532_0
  - openjpeg=2.5.2=hae555c5_0
  - openpyxl=3.1.5=py39h827c3e9_1
  - openssl=1.1.1w=h2bbff1b_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - packaging=25.0=py39haa95532_1
  - pandas=2.3.3=py39ha5e6156_0
  - patsy=1.0.1=py39haa95532_0
  - pillow=11.1.0=py39h096bfcc_0
  - pip=25.3=pyhc872135_0
  - ply=3.11=py39haa95532_0
  - pmdarima=2.0.4=py39h9128911_0
  - propcache=0.3.1=py39h827c3e9_0
  - pyasn1=0.6.1=py39haa95532_0
  - pyasn1-modules=0.4.2=py39haa95532_0
  - pybind11-abi=5=hd3eb1b0_0
  - pycares=4.10.0=py39he29e43d_0
  - pycparser=2.23=py39haa95532_0
  - pyemd=1.0.0=py39hf497b98_0
  - pyparsing=3.2.0=py39haa95532_0
  - pyqt=5.15.10=py39h5da7b33_1
  - pyqt5-sip=12.13.0=py39h827c3e9_1
  - pysocks=1.7.1=py39haa95532_1
  - python=3.9.18=h6244533_0
  - python-dateutil=2.9.0post0=py39haa95532_2
  - python-flatbuffers=24.3.25=py39haa95532_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - pytz=2025.2=py39haa95532_0
  - qt-main=5.15.2=h6072711_9
  - re2=2022.04.01=hd77b12b_0
  - requests=2.32.5=py39haa95532_0
  - requests-oauthlib=2.0.0=py39haa95532_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - scikit-learn=1.5.1=py39hc64d2fc_0
  - scipy=1.13.1=py39h8640f81_1
  - seaborn=0.13.2=py39haa95532_3
  - setuptools=80.9.0=py39haa95532_0
  - sip=6.7.12=py39h5da7b33_1
  - six=1.17.0=py39haa95532_0
  - snappy=1.2.1=hcdb6601_0
  - sqlite=3.51.0=hda9a48d_0
  - statsmodels=0.14.5=py39hf9130e5_0
  - tbb=2021.8.0=h59b6b97_0
  - tensorboard=2.10.0=py39haa95532_0
  - tensorboard-data-server=0.6.1=py39haa95532_0
  - tensorboard-plugin-wit=1.8.1=py39haa95532_0
  - tensorflow=2.10.0=mkl_py39ha510bab_0
  - tensorflow-base=2.10.0=mkl_py39h6a7f48e_0
  - tensorflow-estimator=2.10.0=py39haa95532_0
  - termcolor=2.1.0=py39haa95532_0
  - threadpoolctl=3.5.0=py39h9909e9c_0
  - tk=8.6.15=hf199647_0
  - tomli=2.2.1=py39haa95532_0
  - tornado=6.5.1=py39h827c3e9_0
  - tqdm=4.67.1=py39h9909e9c_0
  - typing-extensions=4.15.0=py39haa95532_0
  - typing_extensions=4.15.0=py39haa95532_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - urllib3=2.5.0=py39haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - werkzeug=3.1.3=py39haa95532_0
  - wheel=0.45.1=py39haa95532_0
  - win_inet_pton=1.1.0=py39haa95532_1
  - winloop=0.2.2=py39h913537a_0
  - wrapt=1.17.0=py39h827c3e9_0
  - xz=5.6.4=h4754444_1
  - yarl=1.18.0=py39h827c3e9_0
  - zipp=3.21.0=py39haa95532_0
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
  - pip:
      - libclang==18.1.1
      - protobuf==3.19.6
      - tensorflow-gpu==2.10.0
      - tensorflow-io-gcs-filesystem==0.31.0
prefix: Q:\Conda_Envs\tf_env
